### ISSUE TITLE
Any plans on update?

### ISSUE THREAD

**Issue by ChanLIM** [uds-lsv/BERT-LNL#1]
Hello authors,
I found your paper very impressive and fascinating.

I was hoping if I could try some of your experiments.
Do you have specific plans on when to upload the code you used in the paper?

Thanks for the great work.

**Comment by davidpig** [comment]
Hi,

Thanks for reaching out.

Yes, although our code is runnable, we would like to clean it up before releasing it. We plan to release it before June.

If you need the code urgently, please write us an email. We may be able to send you some draft code sooner.

Thanks!
